/*
 * SPDX-License-Identifier: GPL-3.0-only
 * MuseScore-Studio-CLA-applies
 *
 * MuseScore Studio
 * Music Composition & Notation
 *
 * Copyright (C) 2026 MuseScore Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#pragma once

#include <functional>
#include <map>
#include <unordered_set>

#include <QHash>
#include <QJsonObject>
#include <QMap>
#include <QString>
#include <QVector>

#include "engraving/editing/undo.h"
#include "engraving/dom/engravingobject.h"
#include "engraving/dom/note.h"
#include "engraving/dom/property.h"
#include "engraving/dom/score.h"
#include "engraving/types/types.h"

namespace mu::engraving {
class Chord;
class ChordRest;
class Clef;
class KeySig;
class Part;
class Rest;
class TempoText;
class Tie;
class TimeSig;
}

namespace mu::editude::internal {
class OperationTranslator
{
public:
    // Translates all local MuseScore changes from one committed undo transaction
    // into a list of OT op payloads ready to be sent to the server.
    //
    // remoteElementToUuid: read-only reverse map from ScoreApplicator; covers
    //   elements that were originally applied from remote ops.
    // The translator maintains its own m_localElementToUuid map for locally-
    //   inserted elements so that subsequent SetPitch / SetTrack / DeleteEvent
    //   ops targeting them can be emitted correctly.
    //
    // Part UUIDs are resolved from m_knownPartUuids. Parts not yet registered
    // (e.g. loaded from MSCX before any OT session) are lazily assigned a UUID
    // and an AddPart op is prepended to the output so the server learns about them.
    QVector<QJsonObject> translateAll(
        const std::map<mu::engraving::EngravingObject*,
                       std::unordered_set<mu::engraving::CommandType>>& changedObjects,
        const mu::engraving::PropertyIdSet& changedPropertyIdSet,
        const QHash<mu::engraving::EngravingObject*, QString>& remoteElementToUuid,
        const QMap<QString, QString>& changedMetaTags = {});

    // Bootstraps m_knownPartUuids for all parts in the score that do not yet
    // have an assigned editude UUID (e.g. parts loaded from an MSCX file).
    // Returns AddPart ops for each newly registered part; the caller should
    // send these to the server so it learns about the pre-existing parts.
    // Also calls registerCallback(part, uuid) for each new part so the caller
    // can register them in its ScoreApplicator.
    QVector<QJsonObject> bootstrapPartsFromScore(
        mu::engraving::Score* score,
        std::function<void(mu::engraving::Part*, const QString&)> registerCallback = {});

    // Register a known part in m_knownPartUuids without emitting an AddPart op.
    // Used to sync part registrations from the applicator (e.g. after sync ops
    // adopt existing parts) so that subsequent translateAll() calls do not
    // generate spurious lazy AddPart ops.
    void registerKnownPart(mu::engraving::Part* part, const QString& uuid);

    // Clear all internal state (part UUIDs, element UUID maps).  Called when
    // reconnecting to a new project so that stale mappings from the previous
    // session do not leak into the new one.
    void reset();

    const QHash<mu::engraving::EngravingObject*, QString>& localElementToUuid() const
    {
        return m_localElementToUuid;
    }

    const QHash<mu::engraving::Part*, QString>& knownPartUuids() const
    {
        return m_knownPartUuids;
    }

private:
    // Resolve the editude UUID for a Part*. If the part is not yet in
    // m_knownPartUuids (e.g. loaded from MSCX), generate a fresh UUID,
    // store it, and append an AddPart op to lazyAddPartOps.
    QString resolvePartUuid(mu::engraving::Part* part,
                            QVector<QJsonObject>& lazyAddPartOps);

    // UUID lookup across both local and remote maps.
    QString uuidForElement(
        mu::engraving::EngravingObject* obj,
        const QHash<mu::engraving::EngravingObject*, QString>& remoteElementToUuid) const;

    // UUID lookup for a ChordRest: checks Chord*/Rest* directly, then falls back to
    // checking the note pointer for single-note InsertNote ops (which store UUID on Note*).
    QString uuidForChordRest(
        mu::engraving::ChordRest* cr,
        const QHash<mu::engraving::EngravingObject*, QString>& remoteElementToUuid) const;

    // Insert builders — take a fresh UUID generated by translateAll.
    QJsonObject buildInsertNote(mu::engraving::Note* note,
                                const QString& uuid, const QString& partId);
    QJsonObject buildInsertRest(mu::engraving::Rest* rest,
                                const QString& uuid, const QString& partId);
    QJsonObject buildInsertChord(mu::engraving::Chord* chord,
                                 const QVector<mu::engraving::Note*>& notes,
                                 const QString& uuid, const QString& partId);

    // Modification / deletion builders.
    static QJsonObject buildAddChordNote(const QString& chordUuid, mu::engraving::Note* note);
    static QJsonObject buildRemoveChordNote(const QString& chordUuid, mu::engraving::Note* note);
    static QJsonObject buildDeleteEvent(const QString& uuid);
    static QJsonObject buildSetPitch(const QString& uuid, mu::engraving::Note* note);
    static QJsonObject buildSetTabNote(const QString& uuid, mu::engraving::Note* note);
    static QJsonObject buildSetNoteHead(const QString& uuid, mu::engraving::Note* note);
    static QJsonObject buildSetTrack(const QString& uuid, mu::engraving::EngravingItem* item);

    // Directive builders.
    static QJsonObject buildSetTimeSignature(mu::engraving::TimeSig* ts);
    static QJsonObject buildSetTempo(mu::engraving::TempoText* tt);
    static QJsonObject buildSetKeySignature(mu::engraving::KeySig* ks, const QString& partUuid);
    static QJsonObject buildSetClef(mu::engraving::Clef* clef, const QString& partUuid,
                                    int staffIdx);
    static QJsonObject buildSetTie(const QString& noteUuid, bool tieStart);

    // Part/staff directive builders (Pass 9+10).
    static QJsonObject buildAddPart(mu::engraving::Part* part,
                                    const QString& uuid);
    static QJsonObject buildRemovePart(const QString& uuid);
    static QJsonObject buildSetPartName(const QString& uuid, const QString& name);
    static QJsonObject buildSetStaffCount(const QString& uuid, int count);
    static QJsonObject buildSetPartInstrument(const QString& uuid,
                                               mu::engraving::Part* part);

    // Tier 3 builders — articulations.
    static QJsonObject buildAddArticulation(mu::engraving::EngravingObject* art,
                                            const QString& uuid, const QString& partId,
                                            const QString& eventUuid);
    static QJsonObject buildRemoveArticulation(const QString& uuid);

    // Tier 3 builders — dynamics.
    static QJsonObject buildAddDynamic(mu::engraving::EngravingObject* dyn,
                                       const QString& uuid, const QString& partId);
    static QJsonObject buildSetDynamic(const QString& uuid, const QString& kind);
    static QJsonObject buildRemoveDynamic(const QString& uuid);

    // Tier 3 builders — slurs.
    static QJsonObject buildAddSlur(mu::engraving::EngravingObject* slur,
                                    const QString& uuid, const QString& partId,
                                    const QString& startEventUuid,
                                    const QString& endEventUuid);
    static QJsonObject buildRemoveSlur(const QString& uuid);

    // Tier 3 builders — hairpins.
    static QJsonObject buildAddHairpin(mu::engraving::EngravingObject* hp,
                                       const QString& uuid, const QString& partId,
                                       const mu::engraving::Fraction& startTick,
                                       const mu::engraving::Fraction& endTick,
                                       bool isCrescendo);
    static QJsonObject buildRemoveHairpin(const QString& uuid);

    // Tier 3 builders — tuplets.
    static QJsonObject buildAddTuplet(mu::engraving::EngravingObject* tup,
                                      const QString& uuid, const QString& partId,
                                      const QVector<QString>& memberUuids,
                                      int actualNotes, int normalNotes);
    static QJsonObject buildRemoveTuplet(const QString& uuid);

    // Tier 3 builders — chord symbols (score-global, no part_id).
    static QJsonObject buildAddChordSymbol(const QString& uuid, int beatNum, int beatDen,
                                           const QString& name);
    static QJsonObject buildSetChordSymbol(const QString& uuid, const QString& name);
    static QJsonObject buildRemoveChordSymbol(const QString& uuid);

    // Tier 3 builders — lyrics.
    static QJsonObject buildAddLyric(mu::engraving::EngravingObject* lyr,
                                     const QString& uuid, const QString& partId,
                                     const QString& eventUuid, int verse,
                                     const QString& syllabic, const QString& text);
    static QJsonObject buildSetLyric(const QString& uuid,
                                     const QString& text, const QString& syllabic);
    static QJsonObject buildRemoveLyric(const QString& uuid);

    // Tier 3 builders — staff text (part-scoped).
    static QJsonObject buildAddStaffText(mu::engraving::EngravingObject* text,
                                         const QString& uuid, const QString& partId);
    static QJsonObject buildSetStaffText(const QString& uuid, const QString& text);
    static QJsonObject buildRemoveStaffText(const QString& uuid);

    // Tier 3 builders — system text (score-global).
    static QJsonObject buildAddSystemText(mu::engraving::EngravingObject* text,
                                          const QString& uuid);
    static QJsonObject buildSetSystemText(const QString& uuid, const QString& text);
    static QJsonObject buildRemoveSystemText(const QString& uuid);

    // Tier 3 builders — rehearsal marks (score-global).
    static QJsonObject buildAddRehearsalMark(mu::engraving::EngravingObject* mark,
                                             const QString& uuid);
    static QJsonObject buildSetRehearsalMark(const QString& uuid, const QString& text);
    static QJsonObject buildRemoveRehearsalMark(const QString& uuid);

    // Advanced spanners — octave lines.
    static QJsonObject buildAddOctaveLine(mu::engraving::EngravingObject* ottava,
                                           const QString& uuid, const QString& partId);
    static QJsonObject buildRemoveOctaveLine(const QString& uuid);

    // Advanced spanners — glissandos.
    static QJsonObject buildAddGlissando(mu::engraving::EngravingObject* gliss,
                                          const QString& uuid, const QString& partId,
                                          const QString& startEventUuid,
                                          const QString& endEventUuid);
    static QJsonObject buildRemoveGlissando(const QString& uuid);

    // Advanced spanners — pedal lines.
    static QJsonObject buildAddPedalLine(mu::engraving::EngravingObject* pedal,
                                          const QString& uuid, const QString& partId);
    static QJsonObject buildRemovePedalLine(const QString& uuid);

    // Advanced spanners — trill lines.
    static QJsonObject buildAddTrillLine(mu::engraving::EngravingObject* trill,
                                          const QString& uuid, const QString& partId);
    static QJsonObject buildRemoveTrillLine(const QString& uuid);

    // Tier 3 builders — arpeggios.
    static QJsonObject buildAddArpeggio(mu::engraving::EngravingObject* arp,
                                         const QString& uuid, const QString& partId,
                                         const QString& eventUuid);
    static QJsonObject buildRemoveArpeggio(const QString& uuid);

    // Grace note builders.
    static QJsonObject buildAddGraceNote(mu::engraving::EngravingObject* graceObj,
                                          const QString& uuid, const QString& partId,
                                          const QString& eventUuid);
    static QJsonObject buildRemoveGraceNote(const QString& uuid);

    // Breath mark / caesura builders.
    static QJsonObject buildAddBreathMark(mu::engraving::EngravingObject* breath,
                                           const QString& uuid, const QString& partId);
    static QJsonObject buildRemoveBreathMark(const QString& uuid);

    // Tier 4 builders — volta.
    static QJsonObject buildInsertVolta(mu::engraving::EngravingObject* volta,
                                        const QString& uuid);
    static QJsonObject buildRemoveVolta(const QString& uuid);

    // Tier 4 builders — markers.
    static QJsonObject buildInsertMarker(mu::engraving::EngravingObject* marker,
                                         const QString& uuid);
    static QJsonObject buildRemoveMarker(const QString& uuid);

    // Tier 4 builders — jumps.
    static QJsonObject buildInsertJump(mu::engraving::EngravingObject* jump,
                                       const QString& uuid);
    static QJsonObject buildRemoveJump(const QString& uuid);

    // Shared helpers.
    static QJsonObject pitchJson(int tpc, int octave);
    static QJsonObject beatJson(const mu::engraving::Fraction& tick);
    static QString durationTypeName(mu::engraving::DurationType dt);

    // Known parts map — used to detect Add/Remove by diffing against score->parts().
    // Key: Part*, Value: editude UUID assigned when AddPart was first emitted.
    QHash<mu::engraving::Part*, QString> m_knownPartUuids;

    // UUID maps for locally-inserted elements.
    // Mirrors ScoreApplicator's maps for elements inserted by this client:
    //   InsertNote  → Note*   keyed by UUID
    //   InsertChord → Chord*  keyed by UUID
    //   InsertRest  → Rest*   keyed by UUID
    QHash<QString, mu::engraving::EngravingObject*> m_localUuidToElement;
    QHash<mu::engraving::EngravingObject*, QString> m_localElementToUuid;
};
} // namespace mu::editude::internal
